Forces vpc elasticsearch due to count issue
Error: Error refreshing state: 2 error(s) occurred:

* module.es.aws_elasticsearch_domain.es_vpc: aws_elasticsearch_domain.es_vpc: value of 'count' cannot be computed
* module.es.aws_elasticsearch_domain.es: aws_elasticsearch_domain.es: value of 'count' cannot be computed